/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvancePayment {
  'id' : bigint,
  'staffId' : bigint,
  'date' : string,
  'note' : string,
  'amount' : number,
}
export interface Animal {
  'id' : bigint,
  'name' : string,
  'serialNumber' : string,
  'notes' : string,
  'animalType' : string,
  'semenDate' : string,
}
export interface BuyerAdvancePayment {
  'id' : bigint,
  'date' : string,
  'amount' : number,
  'reason' : string,
}
export interface Expense {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface MilkRecord {
  'id' : bigint,
  'morningQuantity' : number,
  'morningAmount' : number,
  'eveningFat' : number,
  'eveningAmount' : number,
  'eveningQuantity' : number,
  'date' : string,
  'morningFat' : number,
}
export interface StaffMember {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'monthlySalary' : number,
  'totalAdvancePaid' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface InventoryItem {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'unit' : string,
  'lowStockThreshold' : number,
  'notes' : string,
}
export interface PurchaseRecord {
  'id' : bigint,
  'itemId' : bigint,
  'date' : string,
  'quantity' : number,
  'price' : number,
  'supplierName' : string,
  'notes' : string,
}
export interface UsageRecord {
  'id' : bigint,
  'itemId' : bigint,
  'date' : string,
  'quantity' : number,
  'purpose' : string,
  'notes' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdvancePayment' : ActorMethod<[bigint, string, number, string], bigint>,
  'addAnimal' : ActorMethod<[string, string, string, string, string], bigint>,
  'addBuyerAdvancePayment' : ActorMethod<[string, number, string], bigint>,
  'addExpense' : ActorMethod<[string, string, number, string, string], bigint>,
  'addMilkRecord' : ActorMethod<
    [string, number, number, number, number, number, number],
    bigint
  >,
  'addStaffMember' : ActorMethod<[string, string, number], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAdvancePayment' : ActorMethod<[bigint], undefined>,
  'deleteAnimal' : ActorMethod<[bigint], undefined>,
  'deleteBuyerAdvancePayment' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteMilkRecord' : ActorMethod<[bigint], undefined>,
  'deleteStaffMember' : ActorMethod<[bigint], undefined>,
  'getAdvancePayments' : ActorMethod<[], Array<AdvancePayment>>,
  'getAnimals' : ActorMethod<[], Array<Animal>>,
  'getBuyerAdvancePayments' : ActorMethod<[], Array<BuyerAdvancePayment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMilkRecords' : ActorMethod<[], Array<MilkRecord>>,
  'getStaffMembers' : ActorMethod<[], Array<StaffMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markExpensePaid' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAnimal' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateBuyerAdvancePayment' : ActorMethod<
    [bigint, string, number, string],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [bigint, string, string, number, string, string],
    undefined
  >,
  'updateMilkRecord' : ActorMethod<
    [bigint, string, number, number, number, number, number, number],
    undefined
  >,
  'updateStaffMember' : ActorMethod<
    [bigint, string, string, number],
    undefined
  >,
  'addInventoryItem' : ActorMethod<[string, string, string, number, string], bigint>,
  'updateInventoryItem' : ActorMethod<[bigint, string, string, string, number, string], undefined>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'getInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'addPurchaseRecord' : ActorMethod<[bigint, string, number, number, string, string], bigint>,
  'updatePurchaseRecord' : ActorMethod<[bigint, bigint, string, number, number, string, string], undefined>,
  'deletePurchaseRecord' : ActorMethod<[bigint], undefined>,
  'getPurchaseRecords' : ActorMethod<[], Array<PurchaseRecord>>,
  'addUsageRecord' : ActorMethod<[bigint, string, number, string, string], bigint>,
  'updateUsageRecord' : ActorMethod<[bigint, bigint, string, number, string, string], undefined>,
  'deleteUsageRecord' : ActorMethod<[bigint], undefined>,
  'getUsageRecords' : ActorMethod<[], Array<UsageRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];