/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdvancePayment = IDL.Record({
  'id' : IDL.Nat,
  'staffId' : IDL.Nat,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Animal = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'serialNumber' : IDL.Text,
  'notes' : IDL.Text,
  'animalType' : IDL.Text,
  'semenDate' : IDL.Text,
});
export const BuyerAdvancePayment = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'amount' : IDL.Float64,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const MilkRecord = IDL.Record({
  'id' : IDL.Nat,
  'morningQuantity' : IDL.Float64,
  'morningAmount' : IDL.Float64,
  'eveningFat' : IDL.Float64,
  'eveningAmount' : IDL.Float64,
  'eveningQuantity' : IDL.Float64,
  'date' : IDL.Text,
  'morningFat' : IDL.Float64,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'monthlySalary' : IDL.Float64,
  'totalAdvancePaid' : IDL.Float64,
});


export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'unit' : IDL.Text,
  'lowStockThreshold' : IDL.Float64,
  'notes' : IDL.Text,
});
export const PurchaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'date' : IDL.Text,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
  'supplierName' : IDL.Text,
  'notes' : IDL.Text,
});
export const UsageRecord = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'date' : IDL.Text,
  'quantity' : IDL.Float64,
  'purpose' : IDL.Text,
  'notes' : IDL.Text,
});
export const idlService = IDL.Service({
  'addAdvancePayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addAnimal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addBuyerAdvancePayment' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMilkRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'addStaffMember' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAdvancePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteAnimal' : IDL.Func([IDL.Nat], [], []),
  'deleteBuyerAdvancePayment' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteMilkRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
  'getAdvancePayments' : IDL.Func([], [IDL.Vec(AdvancePayment)], ['query']),
  'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
  'getBuyerAdvancePayments' : IDL.Func(
      [],
      [IDL.Vec(BuyerAdvancePayment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
  'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markExpensePaid' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnimal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateBuyerAdvancePayment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMilkRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateStaffMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdvancePayment = IDL.Record({
    'id' : IDL.Nat,
    'staffId' : IDL.Nat,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Animal = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'serialNumber' : IDL.Text,
    'notes' : IDL.Text,
    'animalType' : IDL.Text,
    'semenDate' : IDL.Text,
  });
  const BuyerAdvancePayment = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'amount' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const MilkRecord = IDL.Record({
    'id' : IDL.Nat,
    'morningQuantity' : IDL.Float64,
    'morningAmount' : IDL.Float64,
    'eveningFat' : IDL.Float64,
    'eveningAmount' : IDL.Float64,
    'eveningQuantity' : IDL.Float64,
    'date' : IDL.Text,
    'morningFat' : IDL.Float64,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'monthlySalary' : IDL.Float64,
    'totalAdvancePaid' : IDL.Float64,
  });
  
  return IDL.Service({
    'addAdvancePayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addAnimal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addBuyerAdvancePayment' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMilkRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'addStaffMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAdvancePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteAnimal' : IDL.Func([IDL.Nat], [], []),
    'deleteBuyerAdvancePayment' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteMilkRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
    'getAdvancePayments' : IDL.Func([], [IDL.Vec(AdvancePayment)], ['query']),
    'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
    'getBuyerAdvancePayments' : IDL.Func(
        [],
        [IDL.Vec(BuyerAdvancePayment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getMilkRecords' : IDL.Func([], [IDL.Vec(MilkRecord)], ['query']),
    'getStaffMembers' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markExpensePaid' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnimal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateBuyerAdvancePayment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMilkRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateStaffMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'addPurchaseRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updatePurchaseRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deletePurchaseRecord' : IDL.Func([IDL.Nat], [], []),
    'getPurchaseRecords' : IDL.Func([], [IDL.Vec(PurchaseRecord)], ['query']),
    'addUsageRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateUsageRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteUsageRecord' : IDL.Func([IDL.Nat], [], []),
    'getUsageRecords' : IDL.Func([], [IDL.Vec(UsageRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };