/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StaffMember {
    id: bigint;
    name: string;
    role: string;
    monthlySalary: number;
    totalAdvancePaid: number;
}
export interface MilkRecord {
    id: bigint;
    morningQuantity: number;
    morningAmount: number;
    eveningFat: number;
    eveningAmount: number;
    eveningQuantity: number;
    date: string;
    morningFat: number;
}
export interface BuyerAdvancePayment {
    id: bigint;
    date: string;
    amount: number;
    reason: string;
}
export interface Expense {
    id: bigint;
    status: string;
    date: string;
    description: string;
    category: string;
    amount: number;
}
export interface AdvancePayment {
    id: bigint;
    staffId: bigint;
    date: string;
    note: string;
    amount: number;
}
export interface UserProfile {
    name: string;
}
export interface Animal {
    id: bigint;
    name: string;
    serialNumber: string;
    notes: string;
    animalType: string;
    semenDate: string;
}

export interface InventoryItem {
    id: bigint;
    name: string;
    category: string;
    unit: string;
    lowStockThreshold: number;
    notes: string;
}
export interface PurchaseRecord {
    id: bigint;
    itemId: bigint;
    date: string;
    quantity: number;
    price: number;
    supplierName: string;
    notes: string;
}
export interface UsageRecord {
    id: bigint;
    itemId: bigint;
    date: string;
    quantity: number;
    purpose: string;
    notes: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addAdvancePayment(staffId: bigint, date: string, amount: number, note: string): Promise<bigint>;
    addAnimal(serialNumber: string, animalType: string, name: string, semenDate: string, notes: string): Promise<bigint>;
    addBuyerAdvancePayment(date: string, amount: number, reason: string): Promise<bigint>;
    addExpense(date: string, description: string, amount: number, category: string, status: string): Promise<bigint>;
    addMilkRecord(date: string, morningQuantity: number, morningFat: number, morningAmount: number, eveningQuantity: number, eveningFat: number, eveningAmount: number): Promise<bigint>;
    addStaffMember(name: string, role: string, monthlySalary: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAdvancePayment(id: bigint): Promise<void>;
    deleteAnimal(id: bigint): Promise<void>;
    deleteBuyerAdvancePayment(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteMilkRecord(id: bigint): Promise<void>;
    deleteStaffMember(id: bigint): Promise<void>;
    getAdvancePayments(): Promise<Array<AdvancePayment>>;
    getAnimals(): Promise<Array<Animal>>;
    getBuyerAdvancePayments(): Promise<Array<BuyerAdvancePayment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpenses(): Promise<Array<Expense>>;
    getMilkRecords(): Promise<Array<MilkRecord>>;
    getStaffMembers(): Promise<Array<StaffMember>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markExpensePaid(id: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAnimal(id: bigint, serialNumber: string, animalType: string, name: string, semenDate: string, notes: string): Promise<void>;
    updateBuyerAdvancePayment(id: bigint, date: string, amount: number, reason: string): Promise<void>;
    updateExpense(id: bigint, date: string, description: string, amount: number, category: string, status: string): Promise<void>;
    updateMilkRecord(id: bigint, date: string, morningQuantity: number, morningFat: number, morningAmount: number, eveningQuantity: number, eveningFat: number, eveningAmount: number): Promise<void>;
    updateStaffMember(id: bigint, name: string, role: string, monthlySalary: number): Promise<void>;
    addInventoryItem(name: string, category: string, unit: string, lowStockThreshold: number, notes: string): Promise<bigint>;
    updateInventoryItem(id: bigint, name: string, category: string, unit: string, lowStockThreshold: number, notes: string): Promise<void>;
    deleteInventoryItem(id: bigint): Promise<void>;
    getInventoryItems(): Promise<Array<InventoryItem>>;
    addPurchaseRecord(itemId: bigint, date: string, quantity: number, price: number, supplierName: string, notes: string): Promise<bigint>;
    updatePurchaseRecord(id: bigint, itemId: bigint, date: string, quantity: number, price: number, supplierName: string, notes: string): Promise<void>;
    deletePurchaseRecord(id: bigint): Promise<void>;
    getPurchaseRecords(): Promise<Array<PurchaseRecord>>;
    addUsageRecord(itemId: bigint, date: string, quantity: number, purpose: string, notes: string): Promise<bigint>;
    updateUsageRecord(id: bigint, itemId: bigint, date: string, quantity: number, purpose: string, notes: string): Promise<void>;
    deleteUsageRecord(id: bigint): Promise<void>;
    getUsageRecords(): Promise<Array<UsageRecord>>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdvancePayment(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdvancePayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdvancePayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addAnimal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnimal(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnimal(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addBuyerAdvancePayment(arg0: string, arg1: number, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBuyerAdvancePayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBuyerAdvancePayment(arg0, arg1, arg2);
            return result;
        }
    }
    async addExpense(arg0: string, arg1: string, arg2: number, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addMilkRecord(arg0: string, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addStaffMember(arg0: string, arg1: string, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffMember(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffMember(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAdvancePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAdvancePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAdvancePayment(arg0);
            return result;
        }
    }
    async deleteAnimal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnimal(arg0);
            return result;
        }
    }
    async deleteBuyerAdvancePayment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBuyerAdvancePayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBuyerAdvancePayment(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteMilkRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilkRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilkRecord(arg0);
            return result;
        }
    }
    async deleteStaffMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaffMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaffMember(arg0);
            return result;
        }
    }
    async getAdvancePayments(): Promise<Array<AdvancePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvancePayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvancePayments();
            return result;
        }
    }
    async getAnimals(): Promise<Array<Animal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimals();
            return result;
        }
    }
    async getBuyerAdvancePayments(): Promise<Array<BuyerAdvancePayment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerAdvancePayments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerAdvancePayments();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return result;
        }
    }
    async getMilkRecords(): Promise<Array<MilkRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilkRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilkRecords();
            return result;
        }
    }
    async getStaffMembers(): Promise<Array<StaffMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffMembers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markExpensePaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markExpensePaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markExpensePaid(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAnimal(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnimal(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnimal(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateBuyerAdvancePayment(arg0: bigint, arg1: string, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBuyerAdvancePayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBuyerAdvancePayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateMilkRecord(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMilkRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateStaffMember(arg0: bigint, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffMember(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffMember(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addInventoryItem(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string): Promise<bigint> {
        if (this.processError) {
            try { const result = await this.actor.addInventoryItem(arg0, arg1, arg2, arg3, arg4); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.addInventoryItem(arg0, arg1, arg2, arg3, arg4); return result; }
    }
    async updateInventoryItem(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.updateInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.updateInventoryItem(arg0, arg1, arg2, arg3, arg4, arg5); return result; }
    }
    async deleteInventoryItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.deleteInventoryItem(arg0); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.deleteInventoryItem(arg0); return result; }
    }
    async getInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try { const result = await this.actor.getInventoryItems(); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.getInventoryItems(); return result; }
    }
    async addPurchaseRecord(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try { const result = await this.actor.addPurchaseRecord(arg0, arg1, arg2, arg3, arg4, arg5); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.addPurchaseRecord(arg0, arg1, arg2, arg3, arg4, arg5); return result; }
    }
    async updatePurchaseRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: number, arg4: number, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.updatePurchaseRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.updatePurchaseRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6); return result; }
    }
    async deletePurchaseRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.deletePurchaseRecord(arg0); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.deletePurchaseRecord(arg0); return result; }
    }
    async getPurchaseRecords(): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try { const result = await this.actor.getPurchaseRecords(); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.getPurchaseRecords(); return result; }
    }
    async addUsageRecord(arg0: bigint, arg1: string, arg2: number, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try { const result = await this.actor.addUsageRecord(arg0, arg1, arg2, arg3, arg4); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.addUsageRecord(arg0, arg1, arg2, arg3, arg4); return result; }
    }
    async updateUsageRecord(arg0: bigint, arg1: bigint, arg2: string, arg3: number, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.updateUsageRecord(arg0, arg1, arg2, arg3, arg4, arg5); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.updateUsageRecord(arg0, arg1, arg2, arg3, arg4, arg5); return result; }
    }
    async deleteUsageRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try { const result = await this.actor.deleteUsageRecord(arg0); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.deleteUsageRecord(arg0); return result; }
    }
    async getUsageRecords(): Promise<Array<UsageRecord>> {
        if (this.processError) {
            try { const result = await this.actor.getUsageRecords(); return result; } catch (e) { this.processError(e); throw new Error("unreachable"); }
        } else { const result = await this.actor.getUsageRecords(); return result; }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
